services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - web_node_modules:/app/node_modules
    environment:
      NEXT_TELEMETRY_DISABLED: "1"

  web-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
    profiles:
      - prod

volumes:
  web_node_modules:
