import { PRESERVED_PARAMS_STORAGE_KEY } from "./query-params-storage-key";

/**
 * Runs in `<head>` before React: persists landing `utm_*` params and intercepts
 * internal link clicks so UTMs survive the hydration gap.
 */
export function queryParamsInlineBootstrapScript(): string {
  const key = JSON.stringify(PRESERVED_PARAMS_STORAGE_KEY);
  return `!function(){try{var k=${key};function isUtm(q){return q.indexOf("utm_")===0}function readStored(){try{var raw=sessionStorage.getItem(k);return raw?JSON.parse(raw):{}}catch(e){return{}}}function filterUtm(o){var out={},p;for(p in o)if(isUtm(p))out[p]=o[p];return out}function captureFromUrl(){var s=location.search;if(!s)return;var p=new URLSearchParams(s),o={},h=!1;p.forEach(function(v,q){if(isUtm(q)){o[q]=v;h=!0}});if(!h)return;var e=readStored();sessionStorage.setItem(k,JSON.stringify(Object.assign({},e,o)))}function isInternal(href){if(!href)return false;var t=href.trim();if(t.indexOf("mailto:")===0||t.indexOf("tel:")===0||t.indexOf("//")===0)return false;if(t.charAt(0)==="#")return true;try{var u=new URL(t,location.href);return u.origin===location.origin}catch(e){return false}}function mergeHref(href,preserved){var filtered=filterUtm(preserved);if(!isInternal(href)||!Object.keys(filtered).length)return href;var url=new URL(href.trim(),location.href);for(var q in filtered)if(!url.searchParams.has(q))url.searchParams.set(q,filtered[q]);return url.pathname+url.search+url.hash}captureFromUrl();document.addEventListener("click",function(ev){if(ev.defaultPrevented||ev.button!==0||ev.metaKey||ev.ctrlKey||ev.shiftKey||ev.altKey)return;var target=ev.target;if(!target||!target.closest)return;var anchor=target.closest("a");if(!anchor)return;var href=anchor.getAttribute("href");if(!href||anchor.target==="_blank"||anchor.hasAttribute("download"))return;var rel=anchor.getAttribute("rel")||"";if(/\\bexternal\\b/i.test(rel))return;var preserved=filterUtm(readStored());if(!Object.keys(preserved).length)return;if(!isInternal(href))return;var trimmed=href.trim();var resolved=new URL(trimmed,location.href);var current=new URL(location.href);var fragmentOnly=trimmed.charAt(0)==="#";var destinationHasQuery=!fragmentOnly&&trimmed.indexOf("?")!==-1;if(resolved.origin===current.origin&&resolved.pathname===current.pathname&&!destinationHasQuery&&resolved.hash)return;var merged=mergeHref(href,preserved);if(merged===href)return;ev.preventDefault();location.assign(merged)},true)}catch(n){}}();`;
}
